# Generated by Django 6.1.1 on 2026-09-17 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presentaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_desactivacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='motivo_desactivacion',
            field=models.CharField(blank=True, choices=[('descontinuado', 'Producto descontinuado'), ('sin_stock', 'Sin stock permanente'), ('baja_rotacion', 'Baja rotación'), ('cambio_proveedor', 'Cambio de proveedor'), ('otro', 'Otro motivo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='motivo_desactivacion_detalle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.ForeignKey(blank=True, db_column='presentacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.presentacion'),
        ),
    ]
