# Generated by Django 6.1.1 on 2026-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('entidad', models.CharField(max_length=80)),
                ('entidad_id', models.IntegerField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auditoria',
                'ordering': ['-fecha'],
            },
        ),
    ]
