# Generated by Django 6.1.1 on 2026-09-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmbralConfiguracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('dias_vencimiento', 'Días para vencimiento'), ('stock_minimo', 'Stock mínimo')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'umbrales_configuracion',
            },
        ),
        migrations.CreateModel(
            name='OrdenReabastecimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_sugerida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_aprobada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('generado_por', models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual')], default='automatico', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'db_table': 'ordenes_reabastecimiento',
            },
        ),
    ]
