# Generated by Django 6.1.1 on 2026-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('riesgo_vencimiento', 'Riesgo de vencimiento'), ('bajo_stock', 'Bajo stock'), ('anomalia', 'Anomalía')], max_length=30)),
                ('mensaje', models.TextField()),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('datos_origen', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('vista', 'Vista'), ('atendida', 'Atendida'), ('descartada', 'Descartada')], default='nueva', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atendida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionCorreo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('destinatario', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('proveedor', models.CharField(default='brevo', max_length=30)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificaciones_correo',
            },
        ),
    ]
