# Generated by Django 6.1.1 on 2026-09-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas', '0001_initial'),
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='lote',
            field=models.ForeignKey(blank=True, db_column='lote_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.lote'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='producto',
            field=models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='notificacioncorreo',
            name='alerta',
            field=models.ForeignKey(blank=True, db_column='alerta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='alertas.alerta'),
        ),
    ]
