const Router = require('express').Router();
const authRoutes = require('./auth');
const usuarioRoutes = require('./usuarios');
const rolRoutes = require('./roles');
const permisoRoutes = require('./permisos');
const categoriaRoutes = require('./categorias');
const productoRoutes = require('./productos');
const unidadMedidaRoutes = require('./unidadesMedida');
const presentacionRoutes = require('./presentaciones');
    const catalogoMarcaRoutes = require('./catalogoMarcas');
    const catalogoValorRoutes = require('./catalogoValores');
    const loteRoutes = require('./lotes');
    const movimientoRoutes = require('./movimientos');
    const ventaRoutes = require('./ventas');
    const importacionVentaRoutes = require('./importacionesVentas');
    const umbralRoutes = require('./umbrales');
    const ordenReabastecimientoRoutes = require('./ordenesReabastecimiento');
    const alertaRoutes = require('./alertas');
    const reporteRoutes = require('./reportes');
    const preferenciaRoutes = require('./preferencias');
    const auditoriaRoutes = require('./auditoria');
    const tiposEnvaseRoutes = require('./tiposEnvase');
    const productoPresentacionRoutes = require('./productoPresentacion');
    const precioRoutes = require('./precio');

Router.use('/auth', authRoutes);
Router.use('/usuarios', usuarioRoutes);
Router.use('/roles', rolRoutes);
Router.use('/permisos', permisoRoutes);
Router.use('/categorias', categoriaRoutes);
Router.use('/productos', productoRoutes);
Router.use('/unidades-medida', unidadMedidaRoutes);
Router.use('/presentaciones', presentacionRoutes);
Router.use('/catalogo-marcas', catalogoMarcaRoutes);
Router.use('/catalogo-valores', catalogoValorRoutes);
Router.use('/lotes', loteRoutes);
Router.use('/movimientos', movimientoRoutes);
Router.use('/ventas', ventaRoutes);
Router.use('/importaciones-ventas', importacionVentaRoutes);
Router.use('/umbrales', umbralRoutes);
Router.use('/ordenes-reabastecimiento', ordenReabastecimientoRoutes);
Router.use('/alertas', alertaRoutes);
Router.use('/reportes', reporteRoutes);
Router.use('/preferencias', preferenciaRoutes);
    Router.use('/auditoria', auditoriaRoutes);
    Router.use('/tipos-envase', tiposEnvaseRoutes);
    Router.use('/presentaciones-niveles', productoPresentacionRoutes);
    Router.use('/precios', precioRoutes);

    module.exports = Router;
