# Generated by Django 6.1.1 on 2026-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=80)),
                ('valor', models.JSONField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'preferencias_usuario',
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('formato', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF')], max_length=10)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('ruta_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reportes_generados',
            },
        ),
    ]
