-- Restaurar las 62 marcas que se eliminaron por error (se usó el archivo 'Correcciones' en vez del original).
-- El Excel original 'catalogo_presentaciones.xlsx' tiene 70 marcas. La BD quedó con 8.
-- Se reinsertan las 62 faltantes.

INSERT INTO catalogo_marcas (nombre) VALUES
    ('ADONAY'),
    ('ADVAN'),
    ('ALFA'),
    ('ASITA'),
    ('ATLAS'),
    ('BIOFORM'),
    ('BLOCK'),
    ('BONITO BLANCO'),
    ('BONITO ROLLO'),
    ('BOXER'),
    ('BRILLO OSITO'),
    ('BRILLOMAR'),
    ('CACER'),
    ('CANDY'),
    ('CHIN CHIN'),
    ('CISNE'),
    ('COINA'),
    ('DARNEL'),
    ('DKOPAS'),
    ('DOÑA GUSTA'),
    ('ECOUTIL'),
    ('ELITE'),
    ('ESENCIAL'),
    ('ESTRELLA'),
    ('FABEB'),
    ('FIRME'),
    ('GEMAPAS'),
    ('HAWAI'),
    ('HEAVY DUTY'),
    ('HOME LIFE STYLE'),
    ('IMPORTADO'),
    ('JOSE MANUEL'),
    ('KEVIN'),
    ('LA NORTEÑITA'),
    ('LA SUPER'),
    ('LUCERO'),
    ('LUNITA'),
    ('LUZ'),
    ('MANTARO'),
    ('MAX VLAGS'),
    ('MERI'),
    ('MILENIUM'),
    ('MISTI'),
    ('MONTE SION'),
    ('MULTIUSO'),
    ('OSITO ALFA'),
    ('PAMOLSA'),
    ('PICAFLOR'),
    ('PLASTIFRE'),
    ('POLYBOARD'),
    ('RENDIPEL'),
    ('ROCA'),
    ('ROJAS'),
    ('SION'),
    ('SUAVE'),
    ('SUPER FAST'),
    ('SUPER TALON'),
    ('TACHITO'),
    ('TROME'),
    ('UNIVERSAL'),
    ('VASO-T'),
    ('VLAG')
ON CONFLICT DO NOTHING;